# -*- coding: utf-8 -*-
"""Copy of notebook6a1823662f

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L38CCM41qxy8XZ9EXDNi9rCh37A6_Kc1
"""

!pip install -U transformers huggingface_hub

"""
Generate synthetic instruction-following dataset for makeup transformation
This creates training data from image pairs (image 0 -> image 1)
Uses batched inference for efficiency
"""

import torch
from PIL import Image
from transformers import AutoProcessor, LlavaForConditionalGeneration
import json
import random
from pathlib import Path
from typing import List, Tuple
from tqdm import tqdm

import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

class MakeupTransformationDatasetGenerator:
    def __init__(self, model_name="llava-hf/llava-1.5-7b-hf", batch_size=8):
        """Initialize LLaVA model for generating transformation descriptions"""
        print(f"Loading {model_name}...")
        self.model = LlavaForConditionalGeneration.from_pretrained(
            model_name,
            torch_dtype=torch.float16,
            device_map="auto"
        )
        self.processor = AutoProcessor.from_pretrained(model_name)
        self.batch_size = batch_size

    def generate_transformation_prompts(self):
        """Create diverse instruction prompts for makeup transformation (image 0 -> image 1)"""
        prompts = [
            "Look at these two images. Describe the makeup transformation from the first image to the second image. What changed?",

            "Compare the makeup in both images. What steps would you take to transform the makeup look from image 1 to image 2?",

            "Analyze the differences in makeup between these two images. Describe what makeup techniques and products you would need to recreate this transformation.",

            "What are the key makeup changes from the first to the second image? List the specific steps to achieve this transformation.",

            "Describe how to go from the makeup look in the first image to the makeup look in the second image. Be specific about colors, techniques, and application.",

            "Create a step-by-step makeup tutorial to transform from the look in image 1 to the look in image 2.",

            "What makeup products and techniques would you change to go from the first look to the second look? Describe the transformation process.",

            "Compare these two makeup looks. What's different about the eyes, lips, face makeup, and overall style? How would you recreate this change?",

            "Describe the before and after makeup transformation. What specific changes were made and how would you replicate them?",

            "If you wanted to transform your makeup from the first image to the second image, what would you do differently? Provide detailed instructions.",
        ]
        return prompts

    def prepare_batch_inputs(self, image_pairs: List[Tuple[str, str]], prompts: List[str]):
        """
        Prepare batched inputs for LLaVA
        Note: LLaVA processes images sequentially in the prompt
        """
        images_list = []
        texts_list = []

        for (img0_path, img1_path), prompt in zip(image_pairs, prompts):
            # Load both images
            img0 = Image.open(img0_path).convert("RGB").resize((256, 256), Image.LANCZOS)
            img1 = Image.open(img1_path).convert("RGB").resize((256, 256), Image.LANCZOS)


            # LLaVA can handle multiple images in sequence
            images_list.append([img0, img1])

            # Create conversation with two images
            conversation = [
                {
                    "role": "user",
                    "content": [
                        {"type": "image"},  # First image
                        {"type": "image"},  # Second image
                        {"type": "text", "text": prompt},
                    ],
                },
            ]

            # Apply chat template
            prompt_text = self.processor.apply_chat_template(
                conversation, add_generation_prompt=True
            )
            texts_list.append(prompt_text)

        return images_list, texts_list

    def generate_batch_descriptions(self, image_pairs: List[Tuple[str, str]], prompts: List[str]):
        """Generate descriptions for a batch of image pairs"""
        images_list, texts_list = self.prepare_batch_inputs(image_pairs, prompts)

        # Flatten images for processor (it expects list of images)
        flat_images = []
        for img_pair in images_list:
            flat_images.extend(img_pair)

        # Process batch
        inputs = self.processor(
            images=flat_images,
            text=texts_list,
            return_tensors="pt",
            padding=True,
        ).to(self.model.device, torch.float16)

        # Generate responses for batch
        outputs = self.model.generate(
            **inputs,
            max_new_tokens=300,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            num_beams=1,  # Greedy for batch efficiency
        )

        # Decode responses
        responses = []
        for output in outputs:
            generated_text = self.processor.decode(output, skip_special_tokens=True)
            # Extract just the response after "ASSISTANT:"
            response = generated_text.split("ASSISTANT:")[-1].strip()
            responses.append(response)

        return responses

    def load_image_pairs(self, pairs_file):
        """
        Load image pairs from a file
        Expected format (JSON):
        [
            {"image_0": "path/to/img0.jpg", "image_1": "path/to/img1.jpg"},
            ...
        ]
        Or CSV format:
        image_0,image_1
        path/to/img0.jpg,path/to/img1.jpg
        """

        with open(pairs_file, 'r') as f:
            data = json.load(f)
            return [(d['image_0'], d['image_1']) for d in data[:5]]


    def create_dataset(self, image_pairs_file, image_dir, output_file, num_prompts_per_pair=2):
        """
        Generate full transformation dataset from your image pairs

        Args:
            image_pairs_file: JSON/CSV file with image pairs
            image_dir: Base directory containing images
            output_file: JSON file to save the dataset
            num_prompts_per_pair: How many different prompts per image pair
        """
        image_dir = Path(image_dir)
        image_pairs = self.load_image_pairs(image_pairs_file)

        print(f"Processing {len(image_pairs)} image pairs...")

        dataset = []
        all_prompts = self.generate_transformation_prompts()

        # Process in batches
        for i in tqdm(range(0, len(image_pairs), self.batch_size)):
            batch_pairs = image_pairs[i:i + self.batch_size]

            # Generate multiple prompts per pair
            for prompt_idx in range(num_prompts_per_pair):
                # Select random prompts for this batch
                batch_prompts = [random.choice(all_prompts) for _ in batch_pairs]

                # Prepare full paths
                batch_pairs_full = [
                    (str(image_dir / p0), str(image_dir / p1))
                    for p0, p1 in batch_pairs
                ]

                try:
                    # Generate batch responses
                    responses = self.generate_batch_descriptions(batch_pairs_full, batch_prompts)

                    # Create dataset entries
                    for (img0, img1), prompt, response in zip(batch_pairs, batch_prompts, responses):
                        data_entry = {
                            "id": f"makeup_transform_{len(dataset)}",
                            "image_0": str(img0),
                            "image_1": str(img1),
                            "conversations": [
                                {
                                    "from": "human",
                                    "value": f"<image>\n<image>\n{prompt}"  # Two images
                                },
                                {
                                    "from": "gpt",
                                    "value": response
                                }
                            ]
                        }
                        dataset.append(data_entry)

                except Exception as e:
                    print(f"\nError processing batch at index {i}: {e}")
                    continue

        # Save dataset
        with open(output_file, 'w') as f:
            json.dump(dataset, f, indent=2)

        print(f"\nDataset created! {len(dataset)} transformation samples saved to {output_file}")
        return dataset

# ============================================
# USAGE EXAMPLE
# ============================================

if __name__ == "__main__":
    # Initialize generator with batch size
    generator = MakeupTransformationDatasetGenerator(
        model_name="llava-hf/llava-1.5-7b-hf",
        batch_size=1  # Process 4 image pairs at once
    )


    # Generate dataset from your image pairs
    # First, create a pairs file (example shown below)
    dataset = generator.create_dataset(
        image_pairs_file="/kaggle/input/image-pairs/image_pairs-2.json",  # Your pairs file
        image_dir="/kaggle/input/ffhq-makeup/FFHQ-Makeup",  # Base directory with all images
        output_file="makeup_transformation_instructions.json",
        num_prompts_per_pair=3  # Generate 3 different prompts per pair
    )

    # Example of what the dataset looks like
    print("\nExample entry:")
    print(json.dumps(dataset[0], indent=2))

# # ============================================
# # CREATE YOUR IMAGE PAIRS FILE
# # ============================================

# """
# Example image_pairs.json format:
# [
#     {
#         "image_0": "natural_look_001.jpg",
#         "image_1": "glam_look_001.jpg"
#     },
#     {
#         "image_0": "no_makeup_002.jpg",
#         "image_1": "evening_makeup_002.jpg"
#     }
# ]

# Or create from directory structure:
# If you have:
#   makeup_images/
#     pair_1_before.jpg
#     pair_1_after.jpg
#     pair_2_before.jpg
#     pair_2_after.jpg

# Use this helper:
# """

# def create_pairs_from_directory(image_dir, output_file):
#     """Helper to create pairs file if you have before/after naming convention"""

#     image_dir = Path(image_dir)
#     print("Sorting through image directories....")
#     image_dir_sub = sorted([image_dir_sub for image_dir_sub in image_dir.iterdir() if image_dir_sub.is_dir()])
#     pairs = []
#     for img in image_dir_sub:
#         before_image = str(img)+"/bare.jpg"
#         after_images = sorted(img.glob("makeup_*.*jpg"))
#         for after_img in after_images:
#             pairs.append({
#                 "image_0": before_image,
#                 "image_1": str(Path(after_img))
#             })

#     with open(output_file, 'w') as f:
#         json.dump(pairs, f, indent=2)

#     print(f"Created pairs file with {len(pairs)} pairs")
#     return pairs

# # Uncomment to use:
# create_pairs_from_directory("/kaggle/input/ffhq-makeup/FFHQ-Makeup", "./image_pairs.json")

# ============================================
# FINE-TUNING ON TRANSFORMATION DATA
# ============================================

"""
After generating your transformation dataset, fine-tune LLaVA:

1. The dataset format is ready for LLaVA training with multiple images

2. Fine-tune with the official LLaVA code:

deepspeed llava/train/train_mem.py \\
    --deepspeed ./scripts/zero3.json \\
    --model_name_or_path llava-hf/llava-1.5-7b-hf \\
    --version v1 \\
    --data_path ./makeup_transformation_instructions.json \\
    --image_folder ./makeup_images \\
    --vision_tower openai/clip-vit-large-patch14-336 \\
    --mm_projector_type mlp2x_gelu \\
    --mm_vision_select_layer -2 \\
    --mm_use_im_start_end False \\
    --mm_use_im_patch_token False \\
    --image_aspect_ratio pad \\
    --bf16 True \\
    --output_dir ./checkpoints/llava-makeup-transform \\
    --num_train_epochs 3 \\
    --per_device_train_batch_size 2 \\
    --gradient_accumulation_steps 8 \\
    --learning_rate 2e-5 \\
    --weight_decay 0. \\
    --warmup_ratio 0.03 \\
    --lr_scheduler_type "cosine" \\
    --logging_steps 1 \\
    --tf32 True \\
    --model_max_length 2048 \\
    --gradient_checkpointing True \\
    --dataloader_num_workers 4 \\
    --lazy_preprocess True \\
    --report_to wandb \\
    --lora_enable True \\
    --lora_r 128 \\
    --lora_alpha 256

Note: Batch size is smaller (2) because we're processing 2 images per sample
"""