# -*- coding: utf-8 -*-
"""IP2P_run_on_test_set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WqnMN5Qqp0IwrXEOhyqSFNK77S1K-OF
"""

!pip install transformers accelerate torch

!pip install git+https://github.com/huggingface/diffusers.git

from google.colab import drive
drive.mount('/content/drive')



import torch
from diffusers import StableDiffusionInstructPix2PixPipeline, EulerAncestralDiscreteScheduler
from PIL import Image

model_id = "/content/drive/MyDrive/insp2p_makeup100_mdl"
# Adjusted to run on GPU with float16 for A100 compatibility
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(model_id, torch_dtype=torch.float16, safety_checker=None)
pipe.to("cuda")
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)

# Placeholder for image input. Please load your image here.
# Example: image = Image.open("path/to/your/image.jpg").convert("RGB")
image = Image.new('RGB', (512, 512), color = 'red') # Placeholder: Replace with your actual image

images = pipe("turn him into cyborg", image=image).images
images[0]



import requests
from PIL import Image
from io import BytesIO

image_url = "https://chris.dilger.me/content/images/2019/07/face.jpg"
response = requests.get(image_url)
image_from_url = Image.open(BytesIO(response.content)).convert("RGB")

# Now, you can use 'image_from_url' as your input image.
# For example, replace 'image = Image.new(...)' in the previous cell with:
# image = image_from_url

display(image_from_url)

image = image_from_url

images = pipe("apply light foundation, red lips, and natural makeup", image=image).images
images[0]

images = pipe("Apply natural foundation, define brows, add vibrant lips, create a playful style.", image=image).images
images[0]



import os

base_dir = "/content/drive/MyDrive/data_sampled"
input_folder = "base_images_sampled"
output_folder = "edited_sampled_deng"
prompts_file = "prompts_sampled.txt"

output_path = os.path.join(base_dir, output_folder)
os.makedirs(output_path, exist_ok=True)

print(f"Base directory: {base_dir}")
print(f"Input folder: {input_folder}")
print(f"Output folder: {output_folder}")
print(f"Prompts file: {prompts_file}")
print(f"Output path created/verified: {output_path}")

from PIL import Image
import os

# Construct full paths
input_dir = os.path.join(base_dir, input_folder)
prompts_file_path = os.path.join(base_dir, prompts_file)

# 1. Load prompts from the text file
try:
    with open(prompts_file_path, 'r') as f:
        prompts = [line.strip() for line in f if line.strip()]
    print(f"Loaded {len(prompts)} prompts from {prompts_file_path}")
except FileNotFoundError:
    print(f"Error: Prompts file not found at {prompts_file_path}")
    prompts = []

# Get list of image files in the input folder
image_files = [f for f in os.listdir(input_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
image_files.sort() # Ensure consistent order

if not image_files:
    print(f"No image files found in {input_dir}")
elif len(image_files) != len(prompts):
    print(f"Warning: Number of images ({len(image_files)}) does not match number of prompts ({len(prompts)}).")
    print("Processing will continue, but ensure prompts and images correspond correctly.")

# 2. Iterate through images, apply prompts, and save results
print(f"Starting bulk inference for {len(image_files)} images...")
for i, image_filename in enumerate(image_files):
    if i < len(prompts): # Only process if a corresponding prompt exists
        image_path = os.path.join(input_dir, image_filename)
        current_prompt = prompts[i]

        try:
            original_image = Image.open(image_path).convert("RGB")
            print(f"Processing image {i+1}/{len(image_files)}: {image_filename} with prompt: '{current_prompt}'")

            # Perform inference
            edited_images = pipe(current_prompt, image=original_image).images
            edited_image = edited_images[0]

            # Save the edited image
            output_filename = f"edited_{os.path.splitext(image_filename)[0]}.png" # Save as PNG
            output_image_path = os.path.join(output_path, output_filename)
            edited_image.save(output_image_path)
            print(f"Saved edited image to: {output_image_path}")

        except Exception as e:
            print(f"Error processing {image_filename}: {e}")
    else:
        print(f"Skipping image {image_filename}: No corresponding prompt found.")

print("Bulk inference completed.")

images = pipe("Apply natural foundation, define brows, add bold red lips, and enhance with dramatic eye makeup to achieve an intense look.", image=image).images
images[0]