# -*- coding: utf-8 -*-
"""ip2p full training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1aonvSsePGv8P45XwDFq48BLazctkjz
"""

! nvidia-smi

! git clone --branch v0.27.0 https://github.com/huggingface/diffusers.git

! python3 -m pip install -e ./diffusers

! python3 -m pip install --no-cache-dir xformers transformers[torch] ftfy datasets tensorboard

! accelerate config default

! huggingface-cli login --token=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

from google.colab import drive
drive.mount('/content/drive')

BASE_MODEL="stabilityai/stable-diffusion-2-1"
OUT_DIR="/content/drive/MyDrive/ip2p_10k_deng"            # where checkpoints/logs will be saved
DATASET_HF="FromTheFarNorth/insp2p_ip2p_10k_deng"      # keep if using a HF dataset (remove if using local folder)

! mkdir -p "$OUT_DIR"

! echo "OUT_DIR=$OUT_DIR"
! echo "DATASET_HF=$DATASET_HF"


! accelerate launch --mixed_precision="fp16" \
  ./diffusers/examples/instruct_pix2pix/train_instruct_pix2pix.py \
  --pretrained_model_name_or_path=stabilityai/stable-diffusion-2-1 \
  --dataset_name="${DATASET_HF}" \
  --output_dir="${OUT_DIR}" \
  --enable_xformers_memory_efficient_attention \
  --resolution=512 --random_flip \
  --train_batch_size=4 --gradient_accumulation_steps=4 --gradient_checkpointing \
  --max_train_steps=2200 --checkpointing_steps=100 --checkpoints_total_limit=3 \
  --learning_rate=1e-05 --max_grad_norm=1 --lr_warmup_steps=20 \
  --conditioning_dropout_prob=0.1 \
  --mixed_precision=fp16 \
  --seed=42 --report_to=tensorboard \
  --original_image_column=before --edit_prompt=prompt --edited_image=after \
  --validation_prompt="Use a light foundation for radiant skin, softly outline the eyebrows, choose a natural lip color, and aim for a clean, elegant finish." \
  --val_image_url="https://raw.githubusercontent.com/YuXinyang-Victor/FTFN_bot/refs/heads/main/bare.jpg" \
  --num_validation_images=1 \
  --validation_epochs=2